MIN_TOPIC_LENGTH = 2
MAX_TOPIC_LENGTH = 20

MIN_TITLE_LENGTH = 5
MAX_TITLE_LENGTH = 50

MIN_QUESTION_LENGTH = 20
MAX_QUESTION_LENGTH = 500

MIN_ANSWER_LENGTH = 2
MAX_ANSWER_LENGTH = 200

MAX_USERNAME_LENGTH = 30
